### ISSUE TITLE
Possibly avoid tooltip scanning

### ISSUE THREAD

**Issue by p3lim** [Phanx/BindsWhen#7]
In 7.1 a few new return types to GetItemInfo was added, particularly `bindType` as #14.  
https://wow.gamepedia.com/API_GetItemInfo

**Comment by Phanx** [comment]
I'll look into it when I have some spare time, but that might be a 
while. The results of tooltip scanning are cached, so it's not actually 
adding that much overhead as-is.

Also, my understanding from the API changes thread on WoWI was that it 
tells you if the item is BoE in general, but *not* whether it's already 
bound to you; BindsWhen doesn't show "BoE" text on such items, or at 
least it shouldn't... honestly at this point it's been about a year 
since I actually played the game, so I'm just assuming it's still 
working since nobody has reported otherwise!

**Comment by armordecai** [comment]
I looked into this. Unfortunately the return value from GetItemInfo isn't very helpful for this situation. Phanx was correct in assuming that it only tells you if the item is BoE, and not whether it's soulbound or not. The return value also says that BoA items are BoP. We could use it to bypass the tooltip scanning for non-binding items, but I don't think it's very important, since we're keeping a cache and not scanning the same item more than once anyway.
